#!/usr/bin/env python3
"""
train.py — strict walk-forward backtest of LinearSVC vs v0 hand-tuned baseline.

For each match K in temporal order (K from 1 to N):
  • Train set = all samples from matches 1..K-1 (only samples that survived
    cold-start; first ~12 matches have 0 train data and are skipped).
  • Test set  = samples from match K.
  • Train CalibratedClassifierCV(LinearSVC) + StandardScaler on train set.
  • Predict probabilities on test set.
  • Compute precision@N where N = min(6, num_starters_per_match) — i.e. the
    same shot quota the worker actually uses in production.
  • Aggregate precision across all backtested matches.

Compare against v0 baseline's 52.78% (from feedback_ml_eval_betting.md).

Output:
  scripts/shot_recommender/v1_svm/reports/svm_backtest_<date>.txt
  scripts/shot_recommender/v1_svm/data/model.json (final model trained on all data)
"""

import csv
import json
import os
import sys
import time
from collections import defaultdict, Counter

# Lazy import sklearn — install instructions in README
try:
    import numpy as np
    from sklearn.svm import LinearSVC
    from sklearn.preprocessing import StandardScaler
    from sklearn.calibration import CalibratedClassifierCV
    from sklearn.pipeline import Pipeline
except ImportError as e:
    print('ERROR: missing sklearn or numpy.', file=sys.stderr)
    print('  source .venv/bin/activate && pip install scikit-learn numpy', file=sys.stderr)
    sys.exit(2)

# Local: shared allocation rules (must mirror worker/lib/allocator.js)
sys.path.insert(0, os.path.dirname(__file__))
from allocator import (
    decide_budget, quota_split, allocate_multi_shot,
    hits_count, BUDGET_TO_PLAYERS,
)

DATA_DIR = os.path.join(os.path.dirname(__file__), 'data')
REPORTS_DIR = os.path.join(os.path.dirname(__file__), 'reports')
os.makedirs(REPORTS_DIR, exist_ok=True)


def load_samples():
    csv_path = os.path.join(DATA_DIR, 'samples.csv')
    with open(csv_path, encoding='utf-8') as f:
        rows = list(csv.DictReader(f))
    return rows


def feature_matrix(rows, feature_keys):
    X = np.array([[float(r[k]) for k in feature_keys] for r in rows], dtype=np.float64)
    y = np.array([int(r['y']) for r in rows], dtype=np.int32)
    return X, y


def fid_to_kickoff(rows):
    """Use fid-order ordering — fids generated by FIFA are roughly time-ordered."""
    # The build_dataset already emitted samples in kickoff-sorted order; we
    # preserve that. Group by fid in insertion order.
    seen = []
    seen_set = set()
    for r in rows:
        if r['fid'] not in seen_set:
            seen.append(r['fid'])
            seen_set.add(r['fid'])
    return seen


def v0_score(row):
    """Reproduce v0 baseline's hand-tuned scoring formula on a sample row.

    Faithful port from scripts/shot_recommender/v0_baseline.py (weights v0.5):
      - on_target/match (norm * 15, capped 100)
      - attempt/match (norm * 10, capped 100)
      - position bonus (FW=100, MF=60, DF=20, GK=0)
      - xG/match — UNAVAILABLE in walk-forward (per-match xG isn't in
        match_stats; production reads cumulative xg from players:{pid} which
        is post-match and would leak). To compensate, we re-normalize the
        remaining 4 weights to sum to 1.0 (instead of 0.90), so v0 isn't
        unfairly handicapped by missing 10% weight that just appears as 0.
      - starter bonus (always 1.0 since we only train on starters)
    """
    ot = float(row['ot_overall']) if float(row['ot_overall']) >= 0 else 0
    att = float(row['att_overall'])
    pos = int(row['position'])
    pos_norm = {3: 100, 2: 60, 1: 20, 0: 0}.get(pos, 30)
    ot_norm = min(100, ot * 15)
    att_norm = min(100, att * 10)
    starter_bonus = 100   # all our samples are starters
    # Re-normalize 0.50 + 0.20 + 0.15 + 0.05 = 0.90 → divide by 0.90 to scale
    # weights back to 1.0 sum. Mathematically identical to dropping xg term
    # and scaling the rest proportionally, which is the fairest comparison
    # for walk-forward backtest.
    raw = 0.50 * ot_norm + 0.20 * att_norm + 0.15 * pos_norm + 0.05 * starter_bonus
    return raw / 0.90


def main():
    import argparse
    ap = argparse.ArgumentParser()
    ap.add_argument('--features', choices=['full','pruned'], default='full',
                    help='full = all 17; pruned = drop redundant/zero-weight (11 features)')
    ap.add_argument('--C', type=float, default=1.0, help='LinearSVC regularization')
    ap.add_argument('--penalty', choices=['l2','l1'], default='l2')
    ap.add_argument('--grid', action='store_true', help='walk-forward over C grid')
    args = ap.parse_args()

    print('Loading samples...')
    rows = load_samples()
    print(f'  {len(rows)} samples')

    with open(os.path.join(DATA_DIR, 'meta.json'), encoding='utf-8') as f:
        meta = json.load(f)

    if args.features == 'pruned':
        # Drop redundant / near-zero-weight signals identified in v1 inspection:
        #  - ot_overall:   redundant with vs_weak/strong/medium split (learned -)
        #  - ot_x_FW/DF:   redundant with is_FW/DF (small mag, opposite sign noise)
        #  - n_vs_*:       3 counts had |w| < 0.03 each
        feature_keys = [
            'ot_vs_weak','ot_vs_strong','ot_vs_medium',
            'att_overall','matches_played',
            'is_FW','is_MF','is_DF','is_GK',
            'opp_gc_per_match','team_favoredness',
        ]
    else:
        feature_keys = meta['features_x']
    print(f'  {len(feature_keys)} features ({args.features}): {feature_keys}')

    # Walk-forward: bucket samples by fid in kickoff order
    fid_order = fid_to_kickoff(rows)
    print(f'  {len(fid_order)} unique fixtures')

    by_fid = defaultdict(list)
    for r in rows: by_fid[r['fid']].append(r)

    # Backtest
    print('\n=== Walk-forward backtest ===')
    precisions = []   # per-fixture precision (Metric A: partial-hit)
    v0_precisions = []
    pass_rate_svm = []  # per-fixture PASS (Metric B: all-or-nothing parlay)
    pass_rate_v0 = []
    detailed = []
    min_train = 30

    for k, fid in enumerate(fid_order):
        train_rows = [r for j, f in enumerate(fid_order) if j < k for r in by_fid[f]]
        test_rows = by_fid[fid]

        if len(train_rows) < min_train:
            continue
        # Need at least one positive AND one negative in train
        n_pos = sum(1 for r in train_rows if int(r['y']) == 1)
        n_neg = len(train_rows) - n_pos
        if n_pos < 5 or n_neg < 5:
            continue
        if len(test_rows) == 0:
            continue

        X_train, y_train = feature_matrix(train_rows, feature_keys)
        X_test, y_test = feature_matrix(test_rows, feature_keys)

        scaler = StandardScaler()
        X_train_s = scaler.fit_transform(X_train)
        X_test_s = scaler.transform(X_test)

        # CalibratedClassifierCV wraps LinearSVC and uses Platt scaling so we
        # can rank by probability — needed for top-K selection.
        # cv = "prefit" would require a separate split; we use cv=3 inner folds.
        try:
            base = LinearSVC(C=args.C, penalty=args.penalty, class_weight='balanced',
                             max_iter=5000, dual='auto' if args.penalty=='l2' else False)
            cv_folds = min(3, n_pos, n_neg)
            if cv_folds < 2:
                continue
            clf = CalibratedClassifierCV(base, method='sigmoid', cv=cv_folds)
            clf.fit(X_train_s, y_train)
        except Exception as e:
            print(f'  fid={fid} train fail: {e}')
            continue

        probs = clf.predict_proba(X_test_s)[:, 1]
        v0_scores = np.array([v0_score(r) for r in test_rows])

        # === Group test_rows by side, compute strong/weak ===
        # All rows in this fixture share the same ah_line + sides.
        # Strong side = the one favored by AH (own_favoredness > 0).
        # team_favoredness in the row is already player-perspective.
        home_rows = [(i, r) for i, r in enumerate(test_rows) if r['side'] == 'home']
        away_rows = [(i, r) for i, r in enumerate(test_rows) if r['side'] == 'away']
        if not home_rows or not away_rows:
            continue
        # team_favoredness is the same for all players on a side; pick any.
        home_fav = float(home_rows[0][1]['team_favoredness'])
        away_fav = float(away_rows[0][1]['team_favoredness'])
        if home_fav >= away_fav:
            strong_side_rows = home_rows
            weak_side_rows = away_rows
            strong_fav = home_fav
        else:
            strong_side_rows = away_rows
            weak_side_rows = home_rows
            strong_fav = away_fav

        # Team attacking capacity: sum of ot_overall for each side's starters.
        home_cap = sum(max(0, float(r['ot_overall'])) for _, r in home_rows)
        away_cap = sum(max(0, float(r['ot_overall'])) for _, r in away_rows)
        ah_line_estimate = strong_fav   # magnitude only matters for budget
        budget = decide_budget(home_cap, away_cap, ah_line_estimate, side_is_home_strong=(home_fav >= away_fav))
        max_players = BUDGET_TO_PLAYERS[budget]
        strong_quota, weak_quota = quota_split(budget, strong_fav)
        # max_players for each side, proportional to their quota
        strong_max_p = max(1, round(max_players * strong_quota / budget)) if strong_quota > 0 else 0
        weak_max_p = max_players - strong_max_p
        if weak_quota == 0:
            weak_max_p = 0
        # Build scored pools by side
        def _scored_pool(side_rows, score_fn_idx):
            arr = []
            for orig_idx, r in side_rows:
                arr.append((r, float(score_fn_idx[orig_idx])))
            arr.sort(key=lambda x: x[1], reverse=True)
            return arr
        svm_strong = _scored_pool(strong_side_rows, probs)
        svm_weak = _scored_pool(weak_side_rows, probs)
        v0_strong = _scored_pool(strong_side_rows, v0_scores)
        v0_weak = _scored_pool(weak_side_rows, v0_scores)

        actual_by_pid = {r['pid']: int(r['shots_on_target_actual']) for r in test_rows}

        svm_alloc = (allocate_multi_shot(svm_strong, strong_quota, strong_max_p)
                     + allocate_multi_shot(svm_weak, weak_quota, weak_max_p))
        v0_alloc = (allocate_multi_shot(v0_strong, strong_quota, strong_max_p)
                    + allocate_multi_shot(v0_weak, weak_quota, weak_max_p))

        svm_hits = hits_count(svm_alloc, actual_by_pid)
        v0_hits  = hits_count(v0_alloc,  actual_by_pid)
        precisions.append(svm_hits / budget)
        v0_precisions.append(v0_hits / budget)

        # === Metric B: match-level PASS rate (parlay-style "all-or-nothing") ===
        # PASS iff every recommended player's actual_st >= assigned shots.
        # Models real-world parlay bet: one player failing = whole bet lost.
        def is_pass(alloc):
            for p, shots in alloc:
                pid = str(p.get('pid'))
                actual = actual_by_pid.get(pid, 0)
                if actual < shots:
                    return False
            return True
        svm_pass = 1 if is_pass(svm_alloc) else 0
        v0_pass = 1 if is_pass(v0_alloc) else 0
        pass_rate_svm.append(svm_pass)
        pass_rate_v0.append(v0_pass)

        detailed.append({
            'fid': fid, 'train_n': len(train_rows), 'test_n': len(test_rows),
            'pos_rate_train': n_pos / len(train_rows),
            'budget': budget, 'max_players': max_players,
            'strong_q': strong_quota, 'weak_q': weak_quota,
            'svm_hits': svm_hits, 'v0_hits': v0_hits,
            'svm_precision': svm_hits / budget,
            'v0_precision': v0_hits / budget,
            'svm_pass': svm_pass, 'v0_pass': v0_pass,
            'svm_alloc': [
                {'name': p['name'], 'cc': p['cc'], 'shots_assigned': s,
                 'actual_st': actual_by_pid.get(p['pid'], 0)}
                for p, s in svm_alloc
            ],
            'v0_alloc': [
                {'name': p['name'], 'cc': p['cc'], 'shots_assigned': s,
                 'actual_st': actual_by_pid.get(p['pid'], 0)}
                for p, s in v0_alloc
            ],
        })

    if not precisions:
        print('NO BACKTESTABLE FIXTURES — too few training samples')
        sys.exit(1)

    overall = sum(precisions) / len(precisions)
    v0_overall = sum(v0_precisions) / len(v0_precisions)
    svm_pass_rate = sum(pass_rate_svm) / len(pass_rate_svm)
    v0_pass_rate = sum(pass_rate_v0) / len(pass_rate_v0)
    print(f'\n=== Result (allocator-aware backtest: budget 6/7/8, quota 6-0/5-1/4-2/3-3, max 4-5 players) ===')
    print(f'  backtested fixtures: {len(precisions)}')
    print(f'\n  Metric A — partial-hit precision (单注独立投注):')
    print(f'    SVM: {overall*100:.2f}%   v0: {v0_overall*100:.2f}%   delta: {"+" if (overall-v0_overall)>=0 else ""}{(overall-v0_overall)*100:.2f}pp')
    print(f'\n  Metric B — match-PASS rate (串关全中才算 PASS):')
    print(f'    SVM: {svm_pass_rate*100:.2f}% ({sum(pass_rate_svm)}/{len(pass_rate_svm)} matches PASS)')
    print(f'    v0:  {v0_pass_rate*100:.2f}% ({sum(pass_rate_v0)}/{len(pass_rate_v0)} matches PASS)')
    print(f'    delta: {"+" if (svm_pass_rate-v0_pass_rate)>=0 else ""}{(svm_pass_rate-v0_pass_rate)*100:.2f}pp')
    print(f'\n  random baseline (positive rate): {meta["positive_rate"]*100:.1f}%')
    delta = (overall - v0_overall) * 100
    print(f'  SVM vs v0 (same fixtures, same allocator): {"+" if delta>=0 else ""}{delta:.2f}pp')

    # Train final model on ALL data → export for worker.
    # Single SVC + single Platt calibrator (instead of 5-fold ensemble) so
    # the exported (coef, intercept, platt_a, platt_b) is mathematically
    # equivalent to what worker JS computes. The old cv=5 ensemble averaged
    # 5 different SVC decision boundaries — not equivalent to sklearn's
    # ensemble predict_proba (which averages per-fold probabilities).
    print('\n=== Training final model on all 529 samples for worker export ===')
    from sklearn.model_selection import train_test_split
    from sklearn.frozen import FrozenEstimator
    X_all, y_all = feature_matrix(rows, feature_keys)
    scaler_final = StandardScaler()
    X_all_s = scaler_final.fit_transform(X_all)
    X_train_final, X_cal, y_train_final, y_cal = train_test_split(
        X_all_s, y_all, test_size=0.2, stratify=y_all, random_state=42
    )
    base = LinearSVC(C=args.C, penalty=args.penalty, class_weight='balanced',
                     max_iter=5000, dual='auto' if args.penalty=='l2' else False)
    base.fit(X_train_final, y_train_final)
    clf_final = CalibratedClassifierCV(FrozenEstimator(base), method='sigmoid', cv=None)
    clf_final.fit(X_cal, y_cal)

    # Single SVC + single calibrator. Extract directly — no averaging.
    coef_avg = base.coef_[0].tolist()
    intercept_avg = float(base.intercept_[0])
    only_cc = clf_final.calibrated_classifiers_[0]
    platt_a = float(only_cc.calibrators[0].a_)
    platt_b = float(only_cc.calibrators[0].b_)

    model_export = {
        'version': 'v1_svm_linear_calibrated',
        'features': feature_keys,
        'coef': coef_avg,
        'intercept': intercept_avg,
        'platt_a': platt_a,
        'platt_b': platt_b,
        'scaler_mean': scaler_final.mean_.tolist(),
        'scaler_scale': scaler_final.scale_.tolist(),
        'n_train_samples': int(len(y_all)),
        'positive_rate': float(y_all.mean()),
        'trained_at': time.strftime('%Y-%m-%dT%H:%M:%S+00:00', time.gmtime()),
        'backtest_precision_at_6': overall,
        'backtest_n_fixtures': len(precisions),
    }
    model_path = os.path.join(DATA_DIR, 'model.json')
    with open(model_path, 'w', encoding='utf-8') as f:
        json.dump(model_export, f, indent=2, ensure_ascii=False)
    print(f'  wrote {model_path}')

    # Write detailed backtest report
    report_path = os.path.join(REPORTS_DIR, f'svm_backtest_{time.strftime("%Y%m%d_%H%M")}.txt')
    with open(report_path, 'w', encoding='utf-8') as f:
        f.write(f'SVM v1 walk-forward backtest\n')
        f.write(f'Trained at: {time.strftime("%Y-%m-%d %H:%M UTC", time.gmtime())}\n')
        f.write(f'Samples: {len(rows)}, fixtures: {len(fid_order)}\n')
        f.write(f'Features ({len(feature_keys)}): {feature_keys}\n\n')
        f.write(f'Backtested fixtures: {len(precisions)}\n')
        f.write(f'SVM precision (hits/budget): {overall*100:.2f}%\n')
        f.write(f'v0  precision (hits/budget): {v0_overall*100:.2f}%\n')
        f.write(f'SVM vs v0 (same fixtures, same allocator): {"+" if delta>=0 else ""}{delta:.2f}pp\n\n')
        f.write('=== Per-fixture breakdown ===\n')
        for d in detailed:
            f.write(f'\n{d["fid"]} budget={d["budget"]} (max {d["max_players"]} players, '
                    f'quota {d["strong_q"]}-{d["weak_q"]}) '
                    f'SVM:{d["svm_hits"]}/{d["budget"]}={d["svm_precision"]*100:.0f}% '
                    f'v0:{d["v0_hits"]}/{d["budget"]}={d["v0_precision"]*100:.0f}%\n')
            f.write(f'  SVM picks:\n')
            for a in d['svm_alloc']:
                mark = '✓' if a['actual_st'] >= a['shots_assigned'] else ('~' if a['actual_st'] >= 1 else '✗')
                f.write(f'    {mark} {a["name"]:25s} cc={a["cc"]} assigned={a["shots_assigned"]} actual_st={a["actual_st"]}\n')
            f.write(f'  v0 picks:\n')
            for a in d['v0_alloc']:
                mark = '✓' if a['actual_st'] >= a['shots_assigned'] else ('~' if a['actual_st'] >= 1 else '✗')
                f.write(f'    {mark} {a["name"]:25s} cc={a["cc"]} assigned={a["shots_assigned"]} actual_st={a["actual_st"]}\n')
    print(f'  wrote {report_path}')


if __name__ == '__main__':
    main()
